Created the youtube clone page as the requirements
mateomh/Youtube-Clone pull request #1
Opened 2020-07-08 21:49 UTC by mateomh

Created the fixed navbar with the logo, search bar and buttons.
Created the video display section with the title, view count, social buttons and creator information.
Created the sidebar with the playlist for the next videos.

2020-07-08 22:01 UTC, expjazz requested changes
## Hey @mateomh  and @rgcavalheiro 

#### The repo does not have a readme, so I need to mark it as invalid. I also noted that the numbers of commits were too low. I also advise using the word 'add' in the commits, like: add styling to the content section, instead of 'Style the content section, Start the playlist section'.


### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:

2020-07-09 00:02 UTC, elmejdki requested changes
# status: require changes :recycle: 
## Great job so far guys :clap: but you need to work more on your clone in order to make it look better. :hammer: :wrench: :toolbox: 

- [x] you are missing a live demo link please add one, you can use [githack](https://raw.githack.com/) to generate a new link.

- [x] change the size of the search image

- [x] you are messing the comments section please add it.

- [x] you have a lot of space between the video and the sidebar please fix it.
![image](https://user-images.githubusercontent.com/34653764/86981507-b0888b00-c17e-11ea-90a8-3f76add7d4dc.png)

- [x] align the title of the video with the video thumbnail 

### clone:
![image](https://user-images.githubusercontent.com/34653764/86981578-d9a91b80-c17e-11ea-8382-6fb4da2bcf65.png)

### original:
![image](https://user-images.githubusercontent.com/34653764/86981591-e3cb1a00-c17e-11ea-86a6-7b60652e6d61.png)

- [x] also use proper video titles and author names not just 'video title'

- [x] beneath the video you need to have the same title as in the original page, also the number of views and date should have grey color and smaller font-size:
![image](https://user-images.githubusercontent.com/34653764/86981688-386e9500-c17f-11ea-9184-b09f9b994a32.png)


- [x] Make this icons a little bit smaller:
![image](https://user-images.githubusercontent.com/34653764/86981702-445a5700-c17f-11ea-81d7-1f0c12d3581e.png)

- [x] align the channel image, title and subscribe button like in the original page:
### clone:
![image](https://user-images.githubusercontent.com/34653764/86981752-62c05280-c17f-11ea-9a7f-f650a5962ad6.png)

### original:
![image](https://user-images.githubusercontent.com/34653764/86981758-6b188d80-c17f-11ea-9542-2e0fdb8b8416.png)

### Please make the required changes before requesting another code review.
## Happy Coding :tophat:

2020-07-09 00:02 UTC, elmejdki commented on README.md
> +- Github: [@rgcavalheiro](https://github.com/githubhandle)
Please add also Linkedin and twitter profile links

2020-07-09 00:02 UTC, elmejdki commented on README.md
> +![screenshot](./screenshot.png)
you should use the screenshot of your clone, not the original website please change it

2020-07-10 18:02 UTC, BrittanyBlake approved these changes
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****

 Good Luck and Happy Coding! 🍀 👩🏾‍💻

2020-07-10 18:51 UTC, merged